language: python
python:
  - "3.6"
  - "3.7"
install:
  - make install
  - make install-dev
  - go get github.com/errata-ai/vale
script:
  - vale --ext='.rst' --glob='*.rst' src/docs
  - make lint
  - make test
